[package]
name = "milera-server"
version = "0.1.0"
edition = "2024"

[dependencies]
milera-common = { path = "../../crates/milera-common", features = [ "server" ] }
rust_decimal = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
bcrypt = "0.17.1"
chrono = { workspace = true }
dashmap = "6.1.0"
jsonwebtoken = "9.3.1"
once_cell = "1.21.3"
serde_json = { workspace = true }
thiserror = "2.0.16"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["chrono", "env-filter", "json", "serde"] }
ulid = "1.2.1"
tower-http = { version = "0.6.6", features = ["cors"] }
jsonrpsee = { workspace = true, features = ["server", "server-core", "macros"] }
anyhow = "1.0.99"
tower = "0.5.2"
hyper = { version = "1.7.0", features = ["http1"] }
url = "2.5.7"
futures = "0.3.31"
serde_qs = "0.15.0"
