[package]
name = "milera-server"
version = "0.1.0"
edition = "2024"

[dependencies]
milera-common = { path = "../../crates/milera-common", features = [ "server" ] }
rust_decimal = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
axum = { version = "0.8.4", features = ["macros", "multipart", "ws"] }
bcrypt = "0.17.1"
chrono = { workspace = true }
dashmap = "6.1.0"
jsonwebtoken = "9.3.1"
once_cell = "1.21.3"
serde_json = "1.0.143"
thiserror = "2.0.16"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["chrono", "env-filter", "json", "serde"] }
ulid = "1.2.1"
