[package]
name = "milera-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["macros", "multipart", "ws"] }
bcrypt = "0.17.1"
chrono = { version = "0.4.41", features = ["serde"] }
dashmap = "6.1.0"
jsonwebtoken = "9.3.1"
once_cell = "1.21.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
sqlx = { version = "0.8.6", features = ["chrono", "postgres", "runtime-tokio"] }
thiserror = "2.0.16"
tokio = { workspace = true }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["chrono", "env-filter", "json", "serde"] }
ulid = "1.2.1"
